// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fujafrmmyvtsvhqehelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1amFmcm1teXZ0c3ZocWVoZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDgxOTUsImV4cCI6MjA2NzEyNDE5NX0.1RexU0lwEigkMsa-rG4Am4QHW0OvEROpdY5AfHgi7iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});